force-app/main/default/objects/Steps__c/Steps__c.object-meta.xml
<CustomObject>
    <label>Steps</label>
    <pluralLabel>Steps</pluralLabel>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Steps__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <type>Lookup</type>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contact_Steps</relationshipName>
</CustomField>

force-app/main/default/objects/Steps__c/fields/Golden_Point__c.field-meta.xml
<CustomField>
    <fullName>Golden_Point__c</fullName>
    <label>Golden Point</label>
    <type>Number</type>
    <precision>5</precision>
    <scale>2</scale>
</CustomField>

force-app/main/default/objects/Steps__c/fields/Penalty__c.field-meta.xml
<CustomField>
    <fullName>Penalty__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Penalty</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Steps__c/fields/Streak__c.field-meta.xml
<CustomField>
    <fullName>Streak__c</fullName>
    <label>Streak</label>
    <type>Number</type>
    <description>Tracks the continuous streak of steps taken</description>
    <inlineHelpText>The number of consecutive days steps have been recorded</inlineHelpText>
    <precision>8</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/objects/Steps__c/fields/Todays_Steps__c.field-meta.xml
<CustomField>
    <fullName>Todays_Steps__c</fullName>
    <label>Today's Steps</label>
    <type>Number</type>
    <precision>10</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/objects/Steps__c/fields/Total_Steps__c.field-meta.xml
<CustomField>
    <fullName>Total_Steps__c</fullName>
    <label>Total Steps</label>
    <type>Number</type>
    <precision>10</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/classes/Steps/Steps_CON.cls
/**
 * @description       : 
 * @author            : $username  Deloitte
 * @date              : 02-05-2025
 * @group             : ITBA
 * @last modified on  : 02-05-2025
 * @last modified by  : Shubham Raut
**/
public with sharing class Steps_CON {
    @AuraEnabled
    public static string upsertSteps(String payload){
        try {
            if(Steps_SRV.upsertSteps(payload)){
                return 'SUCCESS';
            }
            return 'FAILURE';
        } catch (Exception e) {
            return 'FAILURE';
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Steps__c> getStepsData(){
        try {
            List<Steps__c> steps = [SELECT Id, Name, Total_Steps__c, Penalty__c, Golden_Point__c, Contact__r.Name, Contact__c, Todays_Steps__c, Streak__c FROM Steps__c WHERE Contact__r.Account.Name = 'Step Competition'];
            if(steps != null)
                return steps;
            return new List<Steps__c>();
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}