force-app/main/default/objects/Steps__c/Steps__c.object-meta.xml
<CustomObject>
    <label>Steps</label>
    <pluralLabel>Steps</pluralLabel>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Steps__c/fields/Golden_Point__c.field-meta.xml
<CustomField>
    <fullName>Golden_Point__c</fullName>
    <label>Golden Point</label>
    <type>Number</type>
    <precision>5</precision>
    <scale>2</scale>
</CustomField>

force-app/main/default/objects/Steps__c/fields/Penalty__c.field-meta.xml
<CustomField>
    <fullName>Penalty__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Penalty</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Steps__c/fields/Streak__c.field-meta.xml
<CustomField>
    <fullName>Streak__c</fullName>
    <label>Streak</label>
    <type>Number</type>
    <description>Tracks the continuous streak of steps taken</description>
    <inlineHelpText>The number of consecutive days steps have been recorded</inlineHelpText>
    <precision>8</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/objects/Steps__c/fields/Todays_Steps__c.field-meta.xml
<CustomField>
    <fullName>Todays_Steps__c</fullName>
    <label>Today's Steps</label>
    <type>Number</type>
    <precision>10</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/objects/Steps__c/fields/Total_Steps__c.field-meta.xml
<CustomField>
    <fullName>Total_Steps__c</fullName>
    <label>Total Steps</label>
    <type>Number</type>
    <precision>10</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/classes/UpdateTotalStepsAndPenalty_TRH.cls
/**
 * @description       : 
 * @author            : Shubham Raut
 * @date              : 02-05-2025
 * @group             : ITBA
 * @last modified on  : 02-05-2025
 * @last modified by  : Shubham Raut
**/
public with sharing class UpdateTotalStepsAndPenalty_TRH {

    public static Boolean skipTrigger = false;

    public static void updateTotalStepsAndPenalty(List<Steps__c> newRecords, Map<Id, Steps__c> oldRecordsMap) {
        if(!skipTrigger){
            List<Steps__c> recordsToProcess = new List<Steps__c>();
            for(Steps__c newRecord: newRecords){
                Steps__c oldRecord = oldRecordsMap.get(newRecord.Id);
                if(oldRecord != null && newRecord.Todays_Steps__c != oldRecord.Todays_Steps__c){
                    Steps__c recordToUpdate = new Steps__c();
                    recordToUpdate.Id = newRecord.Id;
                    recordToUpdate.Penalty__c = (newRecord.Todays_Steps__c - newRecord.Total_Steps__c) < newRecord.Streak__c ? newRecord.Penalty__c + 1 : newRecord.Penalty__c;
                    recordToUpdate.Streak__c = newRecord.Todays_Steps__c - newRecord.Total_Steps__c;
                    recordToUpdate.Total_Steps__c = newRecord.Todays_Steps__c;
                    if(newRecord.Golden_Point__c > 0 && newRecord.Golden_Point__c != oldRecord.Golden_Point__c && recordToUpdate.Streak__c < 25000){
                        recordToUpdate.Golden_Point__c = newRecord.Golden_Point__c - 1;
                    }

                    recordsToProcess.add(recordToUpdate);
                }
            }

            Database.update(recordsToProcess, true);
        }
    }
}