force-app/main/default/objects/Competition__c/Competition__c.object-meta.xml
<CustomObject>
    <label>Competition</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Competition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Steps__c/Steps__c.object-meta.xml
<CustomObject>
    <label>Steps</label>
    <pluralLabel>Steps</pluralLabel>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Steps__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <type>Lookup</type>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contact_Steps</relationshipName>
</CustomField>

force-app/main/default/objects/Steps__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>254</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Steps__c/fields/Golden_Point__c.field-meta.xml
<CustomField>
    <fullName>Golden_Point__c</fullName>
    <label>Golden Point</label>
    <type>Number</type>
    <precision>5</precision>
    <scale>2</scale>
</CustomField>

force-app/main/default/objects/Steps__c/fields/Todays_Steps__c.field-meta.xml
<CustomField>
    <fullName>Todays_Steps__c</fullName>
    <label>Today's Steps</label>
    <type>Number</type>
    <precision>10</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/classes/Steps/Steps_SRV.cls
/**
 * @description       : 
 * @author            : $username  Deloitte
 * @date              : 02-06-2025
 * @group             : ITBA
 * @last modified on  : 02-06-2025
 * @last modified by  : Shubham Raut
**/
public with sharing class Steps_SRV {
    public static Boolean upsertSteps(String payload) {
        if(String.isNotBlank(payload)){
            Steps_WRP.CreateStepsWrapper wrapper = (Steps_WRP.CreateStepsWrapper)JSON.deserialize(payload, Steps_WRP.CreateStepsWrapper.class);
            Steps__c singleRecord = new Steps__c();
            singleRecord.External_ID__c = generateExternalId(wrapper);
            singleRecord.Contact__c = wrapper.contact;
            singleRecord.Todays_Steps__c = wrapper.todaysSteps;
            singleRecord.Competition__c = wrapper.competition;
            if(wrapper.goldenPoint > 0)
                singleRecord.Golden_Point__c = wrapper.goldenPoint;
            
            Schema.SObjectField extField = Steps__c.Fields.External_ID__c;
            Database.upsert(singleRecord, extField, false);
            return true;
        }
        return false;
    }

    private static String generateExternalId(Steps_WRP.CreateStepsWrapper wrapper) {
        String externalId = '';
        externalId = 'EXT~' + wrapper?.competition +'~' + wrapper?.contact;
        return externalId;
    }
}